package validations;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.junit.After;
import org.junit.Before;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;
	
	public class CourtLegacy {	
	  private WebDriver driver;

	  @Before
	  public void setUp() {
		  System.setProperty("webdriver.edge.driver", "drivers\\edgedriver\\msedgedriver.exe"); // Set EdgeDriver property
		  driver = new EdgeDriver(); // Use EdgeDriver
	  }
	  
	  @After
	  public void tearDown() {
//	    driver.quit();
	  }
	  @SuppressWarnings("deprecation")
	@Test
	  public void netshoes() {
	    driver.get("https://www.netshoes.com.br//");
	    driver.findElement(By.cssSelector(".ns-icon-close")).click();
	    {
	      WebElement element = driver.findElement(By.cssSelector(".button"));
	      Actions builder = new Actions(driver);
	      builder.moveToElement(element).perform();
	    }
	    driver.findElement(By.id("search-input")).click();
	    driver.findElement(By.id("search-input")).sendKeys("Tênis nike Court Legacy");
	    driver.findElement(By.cssSelector(".button")).click();
	    assertThat(driver.findElement(By.cssSelector(".smarthint-tracking-card:nth-child(1) .item-card__description__product-name > span")).getText(), is("Tênis Nike Court Legacy Canvas Masculino"));
	    driver.findElement(By.cssSelector(".smarthint-tracking-card:nth-child(1) .loaded")).click();
	    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Tênis Nike Court Legacy Canvas Masculino - Preto"));
	  }
	}


